In [1]:
import pandas as pd

# مسیر دقیق دیتاست پیش‌پردازش شده
dataset_path = r'C:\Users\HsH-HsH\weighted_split_criteria\notebooks\datasets\customer_churn_data_preprocessed.csv'

# بارگذاری دیتاست
df = pd.read_csv(dataset_path)

# نمایش شکل دیتاست و 5 سطر اول برای اطمینان
print("شکل دیتاست:", df.shape)
print(df.head())
print("نام ستون‌ها:", df.columns.tolist())


شکل دیتاست: (896, 8)
    Age  LastTransaction  Churn  Gender_female  Gender_male  \
0  64.0               98      1          False         True   
1  35.0              118      0          False         True   
2  25.0              107      1           True        False   
3  39.0               90      1          False         True   
4  28.0              189      0           True        False   

   Payment Method_cash  Payment Method_cheque  Payment Method_credit card  
0                False                  False                        True  
1                False                   True                       False  
2                False                  False                        True  
3                False                  False                        True  
4                False                   True                       False  
نام ستون‌ها: ['Age', 'LastTransaction', 'Churn', 'Gender_female', 'Gender_male', 'Payment Method_cash', 'Payment Method_cheque', 'Payment Method

In [2]:
# جدا کردن ویژگی‌ها (تمام ستون‌ها به جز 'Churn')
X = df.drop('Churn', axis=1)

# جدا کردن برچسب هدف (ستون 'Churn')
y = df['Churn']

# نمایش ابعاد مجموعه ویژگی‌ها و برچسب هدف
print("ابعاد ویژگی‌ها (X):", X.shape)
print("ابعاد برچسب هدف (y):", y.shape)


ابعاد ویژگی‌ها (X): (896, 7)
ابعاد برچسب هدف (y): (896,)


In [3]:
# وارد کردن کلاس مدل از مسیر src/model
from src.model.weighted_decision_tree import WeightedDecisionTree

# تعیین لیست معیارهای وزندهی (مطابق پروژه شما، در صورت متفاوت بودن تغییر دهید)
criteria_list = ['gini', 'entropy']  # یا معیارهای دقیق پروژه شما

# نمونه‌سازی مدل با پارامترهای مورد نظر
model = WeightedDecisionTree(criteria_list=criteria_list, max_depth=3, min_samples_split=5, positive_label=1)

print("مدل ساخته شد.")

# آموزش مدل با داده‌های numpy شده
model.fit(X.to_numpy(), y.to_numpy())

print("مدل آموزش داده شد.")


ModuleNotFoundError: No module named 'utils'

In [4]:
import sys
import os

project_root = r'C:\Users\HsH-HsH\weighted_split_criteria'
src_path = os.path.join(project_root, 'src')
if src_path not in sys.path:
    sys.path.append(src_path)


In [5]:
from model.weighted_decision_tree import WeightedDecisionTree

criteria_list = ['gini', 'entropy']  # یا معیارهای دقیق پروژه شما

model = WeightedDecisionTree(criteria_list=criteria_list, max_depth=3, min_samples_split=5, positive_label=1)

print("مدل ساخته شد.")

model.fit(X.to_numpy(), y.to_numpy())

print("مدل آموزش داده شد.")


مدل ساخته شد.


AttributeError: 'str' object has no attribute 'calculate_score'

In [6]:
import sys
import os

# مسیر پوشه اصلی پروژه خود را وارد کنید (مسیر خود را جایگزین کنید)
project_root = r'C:\Users\HsH-HsH\weighted_split_criteria'

# مسیر پوشه src
src_path = os.path.join(project_root, 'src')

# افزودن به مسیرهای پایتون اگر هنوز اضافه نشده
if src_path not in sys.path:
    sys.path.append(src_path)

print("مسیر src به sys.path اضافه شد.")


مسیر src به sys.path اضافه شد.


In [7]:
import pandas as pd

# مسیر دقیق دیتاست پیش‌پردازش شده خود را جایگزین کنید
dataset_path = r'C:\Users\HsH-HsH\weighted_split_criteria\notebooks\datasets\customer_churn_data_preprocessed.csv'

# بارگذاری دیتاست
df = pd.read_csv(dataset_path)

# جدا کردن ویژگی‌ها (تمام ستون‌ها به جز 'Churn')
X = df.drop('Churn', axis=1)

# جدا کردن برچسب هدف (ستون 'Churn')
y = df['Churn']

# نمایش ابعاد برای اطمینان
print("ابعاد ویژگی‌ها (X):", X.shape)
print("ابعاد برچسب هدف (y):", y.shape)


ابعاد ویژگی‌ها (X): (896, 7)
ابعاد برچسب هدف (y): (896,)


In [8]:
from criteria.gini import GiniCriterion
from criteria.bhy import BhattacharyyaCriterion
from criteria.cs import ChiSquaredCriterion
from criteria.dkm import DKMCriterion
from criteria.gs import GStatisticCriterion
from criteria.ks import KolmogorovCriterion
from criteria.marsh import MarshallCriterion
from criteria.mch import MultiClassHellingerCriterion
from criteria.ng import NormalizedGainCriterion
from criteria.qg import QuinlanGainCriterion
from criteria.twoing import TwoingCriterion

criteria_list = [
    GiniCriterion(),
    BhattacharyyaCriterion(),
    ChiSquaredCriterion(),
    DKMCriterion(),
    GStatisticCriterion(),
    KolmogorovCriterion(),
    MarshallCriterion(),
    MultiClassHellingerCriterion(),
    NormalizedGainCriterion(),
    QuinlanGainCriterion(),
    TwoingCriterion()
]

from model.weighted_decision_tree import WeightedDecisionTree

model = WeightedDecisionTree(criteria_list=criteria_list, max_depth=3, min_samples_split=5, positive_label=1)

print("مدل با 11 معیار ساخته شد.")


ImportError: cannot import name 'KolmogorovCriterion' from 'criteria.ks' (C:\Users\HsH-HsH\weighted_split_criteria\src\criteria\ks.py)

In [9]:
# ابتدا مطمئن شوید مسیر src به sys.path اضافه شده است
import sys
import os

project_root = r'C:\Users\HsH-HsH\weighted_split_criteria'
src_path = os.path.join(project_root, 'src')
if src_path not in sys.path:
    sys.path.append(src_path)

print("مسیر src به sys.path اضافه شد.")

# ایمپورت کلاس‌های 11 معیار تقسیم وزندهی
from criteria.gini import GiniCriterion
from criteria.bhy import BhattacharyyaCriterion
from criteria.cs import ChiSquaredCriterion
from criteria.dkm import DKMCriterion
from criteria.gs import GStatisticCriterion
from criteria.ks import KolmogorovSmirnovCriterion  # نام اصلاح شده
from criteria.marsh import MarshallCriterion
from criteria.mch import MultiClassHellingerCriterion
from criteria.ng import NormalizedGainCriterion
from criteria.qg import QuinlanGainCriterion
from criteria.twoing import TwoingCriterion

# تعریف لیست 11 معیار به صورت نمونه‌های کلاس‌ها
criteria_list = [
    GiniCriterion(),
    BhattacharyyaCriterion(),
    ChiSquaredCriterion(),
    DKMCriterion(),
    GStatisticCriterion(),
    KolmogorovSmirnovCriterion(),
    MarshallCriterion(),
    MultiClassHellingerCriterion(),
    NormalizedGainCriterion(),
    QuinlanGainCriterion(),
    TwoingCriterion()
]

# ایمپورت مدل WeightedDecisionTree
from model.weighted_decision_tree import WeightedDecisionTree

# نمونه‌سازی مدل با لیست معیارها
model = WeightedDecisionTree(criteria_list=criteria_list, max_depth=3, min_samples_split=5, positive_label=1)

print("مدل با 11 معیار ساخته شد.")


مسیر src به sys.path اضافه شد.


ImportError: cannot import name 'QuinlanGainCriterion' from 'criteria.qg' (C:\Users\HsH-HsH\weighted_split_criteria\src\criteria\qg.py)

In [10]:
# افزودن مسیر src به sys.path (با توجه به مسیر پروژه خودتان آن را اصلاح کنید)
import sys
import os

project_root = r'C:\Users\HsH-HsH\weighted_split_criteria'
src_path = os.path.join(project_root, 'src')
if src_path not in sys.path:
    sys.path.append(src_path)

print("مسیر src به sys.path اضافه شد.")

# وارد کردن تمامی کلاس‌های معیار 11 گانه با نام‌های صحیح کلاس‌ها
from criteria.gini import GiniCriterion
from criteria.bhy import BhattacharyyaCriterion
from criteria.cs import ChiSquaredCriterion
from criteria.dkm import DKMCriterion
from criteria.gs import GStatisticCriterion
from criteria.ks import KolmogorovSmirnovCriterion
from criteria.marsh import MarshallCriterion
from criteria.mch import MultiClassHellingerCriterion
from criteria.ng import NormalizedGainCriterion
from criteria.qg import GainRatioCriterion  # نام اصلاح شده به جای QuinlanGainCriterion
from criteria.twoing import TwoingCriterion

# تعریف لیست معیارها به صورت نمونه کلاس‌ها
criteria_list = [
    GiniCriterion(),
    BhattacharyyaCriterion(),
    ChiSquaredCriterion(),
    DKMCriterion(),
    GStatisticCriterion(),
    KolmogorovSmirnovCriterion(),
    MarshallCriterion(),
    MultiClassHellingerCriterion(),
    NormalizedGainCriterion(),
    GainRatioCriterion(),  # اصلاح شده
    TwoingCriterion()
]

# وارد کردن مدل WeightedDecisionTree
from model.weighted_decision_tree import WeightedDecisionTree

# نمونه‌سازی مدل با 11 معیار
model = WeightedDecisionTree(criteria_list=criteria_list, max_depth=3, min_samples_split=5, positive_label=1)

print("مدل با 11 معیار ساخته شد.")


مسیر src به sys.path اضافه شد.


Press Enter to exit 


مدل با 11 معیار ساخته شد.


In [11]:
model.fit(X.to_numpy(), y.to_numpy())


In [12]:
# آموزش مدل با داده‌ها
model.fit(X.to_numpy(), y.to_numpy())

print("آموزش مدل با موفقیت انجام شد.")


آموزش مدل با موفقیت انجام شد.


In [13]:
predictions = model.predict(X.to_numpy())
print("10 پیش‌بینی اول مدل:")
print(predictions[:10])


10 پیش‌بینی اول مدل:
[1 1 1 1 0 1 1 0 1 1]


In [14]:
# پیش‌بینی با مدل روی داده‌های X
predictions = model.predict(X.to_numpy())
print("10 پیش‌بینی اول مدل:")
print(predictions[:10])

# ارزیابی مدل با استفاده از معیارهای استاندارد از sklearn
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("دقت مدل:", accuracy_score(y, predictions))
print("\nگزارش طبقه‌بندی:\n", classification_report(y, predictions))
print("\nماتریس درهم‌ریختگی:\n", confusion_matrix(y, predictions))


10 پیش‌بینی اول مدل:
[1 1 1 1 0 1 1 0 1 1]
دقت مدل: 0.8504464285714286

گزارش طبقه‌بندی:
               precision    recall  f1-score   support

           0       0.80      0.78      0.79       320
           1       0.88      0.89      0.88       576

    accuracy                           0.85       896
   macro avg       0.84      0.84      0.84       896
weighted avg       0.85      0.85      0.85       896


ماتریس درهم‌ریختگی:
 [[250  70]
 [ 64 512]]
